version: "3.9"
services:
  echo-server-0:
    image: "echo-server:latest"
    environment:
      - ECHO_SERVER_PORT=${ECHO_SERVER_PORT_1}
      - ECHO_SERVER_ID=${ECHO_SERVER_ID_1}
    ports:
      - "${ECHO_SERVER_PORT_1}:${ECHO_SERVER_PORT_1}"