# Echo-server configuration

title = "Load-balancer config"

[[discovery.servers]]
ip = "http://127.0.0.1:8070"
weight = 5

[[discovery.servers]]
ip = "http://127.0.0.1:8071"
weight = 3

[[discovery.servers]]
ip = "http://127.0.0.1:8072"
weight = 1